# Learn more about Opengist configuration here: https://github.com/thomiceli/opengist/blob/master/docs/configuration/index.md

# Set the log level to one of the following: trace, debug, info, warn, error, fatal, panic. Default: warn
log-level: warn

# Set the log output to one or more of the following: `stdout`, `file`. Default: stdout,file
log-output: stdout,file

# Directory where Opengist will store its data. Default: ~/.opengist/
opengist-home: REPLACE_DATA_DIR

# Name of the SQLite database file. Default: opengist.db
db-filename: ../db/sqlite/opengist.db

# Enable or disable the code search index (either `true` or `false`). Default: true
index.enabled: true

# Name of the directory where the code search index is stored. Default: opengist.index
index.dirname: opengist.index

# Default branch name used by Opengist when initializing Git repositories.
git.default-branch: main

# Set the journal mode for SQLite. Default: WAL
sqlite.journal-mode: WAL

# Public URL to access to Opengist
external-url: REPLACE_HOSTNAME

# HTTP server configuration
# Host to bind to. Default: 0.0.0.0
http.host: 0.0.0.0

# Port to bind to. Default: 6157
http.port: REPLACE_SERVER_PORT

# Enable or disable git operations (clone, pull, push) via HTTP (either `true` or `false`). Default: true
http.git-enabled: true

# SSH built-in server configuration
ssh.git-enabled: true

# Host to bind to. Default: 0.0.0.0
ssh.host: 0.0.0.0

# Port to bind to. Default: 7823
ssh.port: 7823

# Public domain for the Git SSH connection, if it has to be different from the HTTP one.
ssh.external-domain: REPLACE_HOSTNAME

# Path or alias to ssh-keygen executable. Default: ssh-keygen
ssh.keygen-executable: ssh-keygen

# OAuth2 configuration URL must be http://opengist.url/oauth/<github|gitlab|gitea|openid-connect>/callback

# To create a new OAuth2 application using GitHub: https://github.com/settings/applications/new
github.client-key:
github.secret:

# To create a new OAuth2 application using Gitlab: https://gitlab.com/-/user_settings/applications
gitlab.client-key:
gitlab.secret:
gitlab.url: https://gitlab.com/
gitlab.name: GitLab

# To create a new OAuth2 application using Gitea: https://gitea.domain/user/settings/applications
gitea.client-key:
gitea.secret:
gitea.url: https://casjay.work/
gitea.name: CasjaysDev GIT Server

# To create a new OAuth2 application using OpenID Connect:
oidc.client-key:
oidc.secret:
oidc.discovery-url: http://auth.example.com/.well-known/openid-configuration

# Custom assets
custom.logo:
custom.favicon:

# The path can be a URL or a relative path to a file in the $opengist-home/custom/ directory
custom.static-links:
#  - name: Gitea
#    path: https://gitea.com
#  - name: Legal notices
#    path: legal.html
